---
title: "Logistic Regression for Enhancer Prediction"
author: 'Shaurya Jauhari (Email: shauryajauhari@gzhmu.edu.cn)'
date: '`r paste(Sys.Date())`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r entire protocol}


mydata <- readRDS("../../Machine_Learning_Deep_Learning/data/ep_data_sample.rds")

set.seed(3)
data_partition <- sample(2, nrow(mydata), replace = TRUE, prob = c(0.8,0.2))
train <- mydata[data_partition==1,]
test <- mydata[data_partition==2,]


#stats::glm

model1 <- glm(formula = train$class~peaks_h3k27ac+peaks_h3k4me3+peaks_h3k4me2+peaks_h3k4me1, 
              data = train, 
              family = "binomial")
summary(model1)


#Prediction
y_estimate <- predict(model1, 
                      test, 
                      type = "response")

# Converting probabilities to labels
prediction_probabilities <- ifelse(y_estimate>0.5, "Non-Enhancer", "Enhancer")

# Confusion matrix
confusion_matrix<- table(Predicted = prediction_probabilities, Actual = test$class)
print(confusion_matrix)

#Misclassification error
misclassfication_error <- 1- sum(diag(confusion_matrix))/sum(confusion_matrix) 
cat("The misclassification error in test data is",
    (round(misclassfication_error*100)), "percent")
```

